// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
)

type Sku struct {
	// 主键_id
	ID int64 `json:"id"`
	// 编号
	Sn string `json:"sn"`
	// 库存
	Stock int32 `json:"stock"`
	// 已分配库存
	AllocatedStock int32 `json:"allocated_stock"`
	// 售价
	Price string `json:"price"`
	// 商品
	ProductID int64 `json:"product_id"`
	// 删除标记
	DeleteFlag bool `json:"delete_flag"`
}

type StockLog struct {
	// 主键_id
	ID int64 `json:"id"`
	// 入库数量
	InQuantity int32 `json:"in_quantity"`
	// 出库数量
	OutQuantity int32 `json:"out_quantity"`
	// 当前库存
	Stock int32 `json:"stock"`
	// SKU
	ProductID int64 `json:"product_id"`
	// 备注
	Memo sql.NullString `json:"memo"`
	// 创建人
	CreateBy sql.NullString `json:"create_by"`
	// 创建日期
	CreationDate sql.NullTime `json:"creation_date"`
	// 最后修改人
	LastUpdatedBy sql.NullString `json:"last_updated_by"`
	// 最后修改日期
	LastUpdatedDate sql.NullTime `json:"last_updated_date"`
	// 删除标记
	DeleteFlag bool `json:"delete_flag"`
}
