// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AdjustInventory(ctx context.Context, arg AdjustInventoryParams) error
	CreateInventory(ctx context.Context, arg CreateInventoryParams) (sql.Result, error)
	CreateInventoryLog(ctx context.Context, arg CreateInventoryLogParams) (sql.Result, error)
	GetSku(ctx context.Context, arg GetSkuParams) (int32, error)
	UpdateInventory(ctx context.Context, arg UpdateInventoryParams) error
}

var _ Querier = (*Queries)(nil)
