// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
)

// 购物车
type Cart struct {
	// 主键_id
	ID int64 `json:"id"`
	// 会员
	UserID sql.NullInt64 `json:"user_id"`
	// 密钥
	CartKey string `json:"cart_key"`
	// 创建人
	CreateBy sql.NullString `json:"create_by"`
	// 创建日期
	CreationDate sql.NullTime `json:"creation_date"`
	// 删除标记
	DeleteFlag bool `json:"delete_flag"`
}

// 购物车项
type CartItem struct {
	// 主键_id
	ID int64 `json:"id"`
	// 购物车
	CartID int64 `json:"cart_id"`
	// SKU
	ProductID int64 `json:"product_id"`
	// 数量
	Quantity int32 `json:"quantity"`
	// 创建人
	CreateBy sql.NullString `json:"create_by"`
	// 创建日期
	CreationDate sql.NullTime `json:"creation_date"`
	// 删除标记
	DeleteFlag bool `json:"delete_flag"`
}
