// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateCart(ctx context.Context, arg CreateCartParams) (sql.Result, error)
	CreateCartItem(ctx context.Context, arg CreateCartItemParams) (sql.Result, error)
	DeleteCart(ctx context.Context, userID sql.NullInt64) error
	DeleteCartAllItem(ctx context.Context, cartID int64) error
	DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) error
	GetCart(ctx context.Context, userID sql.NullInt64) (Cart, error)
	GetCartItem(ctx context.Context, cartID int64) ([]CartItem, error)
	UpdateCart(ctx context.Context, arg UpdateCartParams) error
	UpdateCartItem(ctx context.Context, arg UpdateCartItemParams) error
}

var _ Querier = (*Queries)(nil)
