// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
)

// 订单
type Order struct {
	// 主键_id
	ID int64 `json:"id"`
	// 订单编号
	Sn string `json:"sn"`
	// 订单状态
	Status int32 `json:"status"`
	// 订单金额
	Amount string `json:"amount"`
	// 优惠卷id
	CouponCodeID string `json:"coupon_code_id"`
	// 优惠券折扣
	CouponDiscount string `json:"coupon_discount"`
	// 会员
	UserID int64 `json:"user_id"`
	// 收货人
	Consignee string `json:"consignee"`
	// 地址
	Address string `json:"address"`
	// 电话
	Phone string `json:"phone"`
	// 到期时间
	Expire sql.NullTime `json:"expire"`
	// 类型
	Type int32 `json:"type"`
	// 退款金额
	RefundAmount string `json:"refund_amount"`
	// 配送方式名称
	ShippingMethodName sql.NullString `json:"shipping_method_name"`
	// 配送时间
	ShippingDate sql.NullTime `json:"shipping_date"`
	// 完成日期
	CompleteDate sql.NullTime `json:"complete_date"`
	// 创建日期
	CreationDate sql.NullTime `json:"creation_date"`
	// 删除标记
	DeleteFlag bool `json:"delete_flag"`
}

// 订单项
type OrderItem struct {
	// 主键_id
	ID int64 `json:"id"`
	// 商品编号
	Sn string `json:"sn"`
	// 商品名称
	Name string `json:"name"`
	// 商品价格
	Price int32 `json:"price"`
	// 商品重量
	Weight sql.NullInt32 `json:"weight"`
	// 商品缩略图
	Thumbnail sql.NullString `json:"thumbnail"`
	// 数量
	Quantity int32 `json:"quantity"`
	// 已发货数量
	ShippedQuantity int32 `json:"shipped_quantity"`
	// 已退货数量
	ReturnQuantity int32 `json:"return_quantity"`
	// 订单
	OrderID int64 `json:"order_id"`
	// SKU
	SkuID sql.NullInt64 `json:"sku_id"`
	// 创建人
	CreateBy sql.NullString `json:"create_by"`
	// 创建日期
	CreationDate sql.NullTime `json:"creation_date"`
	// 最后修改人
	LastUpdatedBy sql.NullString `json:"last_updated_by"`
	// 最后修改日期
	LastUpdatedDate sql.NullTime `json:"last_updated_date"`
	// 删除标记
	DeleteFlag bool `json:"delete_flag"`
}
