// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (sql.Result, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (sql.Result, error)
	DeleteOrder(ctx context.Context, id int64) error
	GetAllOrder(ctx context.Context, userID int64) ([]GetAllOrderRow, error)
	GetOrderAllItem(ctx context.Context, orderID int64) ([]GetOrderAllItemRow, error)
	GetOrderByDate(ctx context.Context, arg GetOrderByDateParams) ([]GetOrderByDateRow, error)
	GetOrderByStatus(ctx context.Context, arg GetOrderByStatusParams) ([]GetOrderByStatusRow, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
}

var _ Querier = (*Queries)(nil)
