// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
)

type User struct {
	// 主键_id
	ID int64 `json:"id"`
	// 用户名
	Username string `json:"username"`
	// 密码
	Password string `json:"password"`
	// 姓名
	Name sql.NullString `json:"name"`
	// 头像
	Avatar sql.NullString `json:"avatar"`
	// 性别,0未知,1男,2女性别
	Gender sql.NullInt32 `json:"gender"`
	// 手机
	Mobile sql.NullString `json:"mobile"`
	// 出生日期
	Birth sql.NullTime `json:"birth"`
	// 邮编
	ZipCode sql.NullString `json:"zip_code"`
	// 地址
	Address sql.NullString `json:"address"`
	// E-mail
	Email sql.NullString `json:"email"`
	// 最后登录日期
	LoginDate sql.NullTime `json:"login_date"`
	// 连续登录失败次数
	LoginFailureCount int32 `json:"login_failure_count"`
	// 创建日期
	CreationDate sql.NullTime `json:"creation_date"`
	// 最后修改日期
	LastUpdatedDate sql.NullTime `json:"last_updated_date"`
	// 删除标记
	DeleteFlag bool `json:"delete_flag"`
}
