// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CheckBrand(ctx context.Context, id int64) (CheckBrandRow, error)
	CheckBrandByProductCategory(ctx context.Context, productCategories int64) ([]ProductCategoryBrand, error)
	CheckCategory(ctx context.Context, arg CheckCategoryParams) ([]ProductCategory, error)
	CheckProductCategoryByBrand(ctx context.Context, brands int64) ([]ProductCategoryBrand, error)
	CheckProductImage(ctx context.Context, arg CheckProductImageParams) ([]CheckProductImageRow, error)
	CreateBrand(ctx context.Context, arg CreateBrandParams) (sql.Result, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (sql.Result, error)
	CreateProductCategory(ctx context.Context, arg CreateProductCategoryParams) (sql.Result, error)
	CreateProductCategoryBrand(ctx context.Context, arg CreateProductCategoryBrandParams) (sql.Result, error)
	DeleteBrand(ctx context.Context, arg DeleteBrandParams) error
	DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error
	DeleteProductImg(ctx context.Context, arg DeleteProductImgParams) error
	GetProduct(ctx context.Context, id int64) ([]Product, error)
	GetProductByBrand(ctx context.Context, brandID sql.NullInt64) ([]Product, error)
	GetProductByCategory(ctx context.Context, productCategoryID int64) ([]Product, error)
	GetProductInfoImg(ctx context.Context, productID int64) ([]ProductImage, error)
	InsertProductImage(ctx context.Context, arg InsertProductImageParams) (sql.Result, error)
	ListProductsByBrand(ctx context.Context, arg ListProductsByBrandParams) ([]Product, error)
	ListProductsByProductCategory(ctx context.Context, arg ListProductsByProductCategoryParams) ([]Product, error)
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error)
	UpdateBrand(ctx context.Context, arg UpdateBrandParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
	UpdateProductCategory(ctx context.Context, arg UpdateProductCategoryParams) error
	UpdateProductCategoryOfBrand(ctx context.Context, arg UpdateProductCategoryOfBrandParams) error
	UpdateProductImage(ctx context.Context, arg UpdateProductImageParams) error
}

var _ Querier = (*Queries)(nil)
